# -*- mode: ruby -*-
# vi: set ft=ruby :

## configuration variables ##
N = 3                     # worker node count
k8s_V = '1.30.0-1.1'      # Kubernetes version
ctrd_V = '1.6.31-1'       # Containerd version
## /configuration variables ##

Vagrant.configure("2") do |config|

  #====================#
  # Control-Plane Node #
  #====================#

  config.vm.define "cp-k8s-#{k8s_V[0..5]}" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "cp-k8s-#{k8s_V[0..5]}(manual)"
      vb.cpus = 2
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--groups", "/k8s-U#{k8s_V[0..5]}-ctrd-#{ctrd_V[0..2]}(manual)"]
    end
    cfg.vm.host_name = "cp-k8s"
    cfg.vm.network "private_network", ip: "192.168.1.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true
  end

  #==============#
  # Worker Nodes #
  #==============#

  (1..N).each do |i|
    config.vm.define "w#{i}-k8s-#{k8s_V[0..5]}" do |cfg|
      cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s-#{k8s_V[0..5]}(manual)"
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/k8s-U#{k8s_V[0..5]}-ctrd-#{ctrd_V[0..2]}(manual)"]
      end
      cfg.vm.host_name = "w#{i}-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

end
